import 'package:untitled1/translate/translate_model.dart';

TranslateModel engModel = const TranslateModel(
  Profile: 'Profile',
  About_us: 'About us',
  Change_account_Image: 'Change account Image',
  Change_account_name: 'Change account name',
  Change_app_language: 'Change app language',
  Delete_account: 'Delete account',
  FAQ: 'FAQ',
  Help_Feedback: 'Help Feedback',
  Information: 'Information',
  Log_out: 'Log out',
  MY_CARS: 'MY CARS',
  Settings: 'Settings',
  Support_US: 'Support US',
  WISHLIST: 'WISHLIST',
  next: 'Next',
  onboarding1Description:
      'Where you can see our inventory of used cars or even request us to find your dream car',
  onboarding1Title: 'Buy a car',
  onboarding2Description:
      'Where you can sell you cars with us on the spot for cash or chose to consignment your car with us',
  onboarding2Title: 'Sell a car',
  onboarding3Description:
      'Find the service needed for your car from our approved garages and book instantly',
  onboarding3Title: 'Service your car',
  skip: 'Skip',
  password: 'Password',
  welcomeBack: 'Welcome back to DWD!',
  login: 'Login',
  createAccount: 'Create account',
  forgotPassword: 'Forgot password',
  mobileNumberOrEmail: 'Mobile number or email',
  welcomeText: 'Please login to your account or create new account to continue',
  welcomeToDWD: 'Welcome to DWD',
  back: 'Back',
  loginTitile: 'Login',
  service: 'Service',
  buy: 'Buy',
  booking: 'Booking',
  sell: 'Sell',
  chat: 'Chat',
  generalRepair: 'General\nrepair',
  recovery: 'Recovery',
  specialOffers: 'Special Offers',
  storage: 'Storage\nand Shipping',
  tinting: 'Tinting',
  detailing: 'Detailing', acRepair: 'AC repair',
  allServices: 'All services', battery: 'Battery',
  brakes: 'Brakes', carRent: 'Car rent',
  insurance: 'Insurance',
  intervalService: 'Interval\nservice',
  wheels: 'Wheels and\ntires',
  wrapping: 'Wrapping &\nPPF',
      createOne: ' Create one',
      Dont_have_an_account_q: "Don't have an account?", Already_have_an_account_q: 'Already have an account?',
  trust: 'Trust',
  safety: 'Safety',
  transparency: 'Transparency',
  sellBannerTitle:  'Sell any car in Dubai, UAE -\nLet us take over, and sell\nyour car!',
  sellBanner1:  'We price your car\naccurately, avoiding\nfake offers and fake\nadverts.',
  sellBanner2:  'We ensure legal\ntransactions and full\npayments,\nprotecting you from\nfraud.',
  sellBanner3:    'We secure the best\noffer for your car\nand provide 24/7\nafter-sale support.',
  inStock: 'In Stock',
      serviceContract: 'Service contract',
      warranty: 'Warranty',
      description: 'Description',
      carDetails: 'Car details',
      color: 'Color',
      transmission: 'Transmission',
      motorsTrim: 'Motors Trim',
      body: 'Body',
      kilometers: 'Kilometers',
      regionalSpecs: 'Regional specs',
  year: 'Year',
  call: 'Call',
  moreCars: 'More cars',
  buyCarBannerPath: 'assets/big_banner.png',
      spotText: 'We will evaluate your car and offer the best price, we pay you direct and in cash on the spot',
      spot: 'Sell on the spot',
      consignment: 'Consignment',
      consignmentText:   'We sell your car on your behalf, against a fixed fee and we handle every aspect of the sale on your behalf, listing, documentation, viewing and detailing if needed',
cancel: 'Cancel',
  change: 'Change',
  bodyRepairAndPaint: 'Body repair\nand paint',
  prePuschaseIncpection: 'Pre-purchase\ninspection',
      add: 'Add',
  selectCar: 'Select car',
  addDelivery: 'Add a delivery',
  addPickup: 'Add a pickup',
  email: 'Email',
  extras: 'Extras',
  included: "What's Included",
  book: 'Book',
  bookingText:  'Our workshop is mostly located in Al QUOZ\narea, we will forward the exact address\nvia what’s app after appointment is confirmed',
  mobilePhone: 'Phone number',
  ownerEmail: 'Owner email',
  ownerName: 'Owner name',
  ownerPhone: 'Owner phone',
  selectDate:   'Select Preferred Date & Time',
  send: 'Send',
  was: 'was',
  stillForSale: 'Still for sale?',
  whereCarIViewIt: 'Where can I view it?',
  isExchangePosible: 'Is exchange posible?',
  fullServiceHistory: 'Full service history',
  noAccident: 'No Accident',
  carName: 'Car name',
  carReg: 'Car Reg/ Plate Number',giveCarName: 'Give car name', brand: 'Car brand',
  newCar: 'New car',
  model: 'Model',

);
