import 'package:untitled1/translate/translate_model.dart';

TranslateModel engModel = const TranslateModel(
  Profile: 'Profile',
  About_us: 'About us',
  Change_account_Image: 'Change account Image',
  Change_account_name: 'Change account name',
  Change_app_language: 'Change app language',
  Delete_account: 'Delete account',
  FAQ: 'FAQ',
  Help_Feedback: 'Help Feedback',
  Information: 'Information',
  Log_out: 'Log out',
  MY_CARS: 'MY CARS',
  Settings: 'Settings',
  Support_US: 'Support US',
  WISHLIST: 'WISHLIST',
  next: 'Next',
  onboarding1Description:
      'Where you can see our inventory of used cars or even request us to find your dream car',
  onboarding1Title: 'Buy a car',
  onboarding2Description:
      'Where you can sell you cars with us on the spot for cash or chose to consignment your car with us',
  onboarding2Title: 'Sell a car',
  onboarding3Description:
      'Find the service needed for your car from our approved garages and book instantly',
  onboarding3Title: 'Service your car',
  skip: 'Skip',
  password: 'Password',
  welcomeBack: 'Welcome back to DWD!',
  login: 'Login',
  createAccount: 'Create account',
  forgotPassword: 'Forgot password',
  mobileNumberOrEmail: 'Mobile number or email',
  welcomeText: 'Please login to your account or create new account to continue',
  welcomeToDWD: 'Welcome to DWD',
  back: 'Back',
  loginTitile: 'Login',
  service: 'Service',
  buy: 'Buy',
  booking: 'Booking',
  sell: 'Sell',
  chat: 'Chat',
  generalRepair: 'General\nrepair',
  recovery: 'Recovery',
  specialOffers: 'Special Offers',
  storage: 'Storage',
  tinting: 'Tinting',
  detailing: 'Detailing', acRepair: 'AC repair',
  allServices: 'All services', battery: 'Battery',
  brakes: 'Brakes', carRent: 'Car rent',
  insurance: 'Insurance',
  intervalService: 'Interval\nservice',
  wheels: 'Wheels and\ntires',
  wrapping: 'Wrapping &\nPPF'

);
