import 'package:untitled1/translate/translate_model.dart';

TranslateModel ruModel = const TranslateModel(
    Profile: 'Профиль',
    About_us: 'О приложении',
    Change_account_Image: 'Изменить фото профиля',
    Change_account_name: 'Изменить имя',
    Change_app_language: 'Сменить язык',
    Delete_account: 'Удалить аккаунт',
    FAQ: 'FAQ',
    Help_Feedback: 'Обратная связь',
    Information: 'Информация',
    Log_out: 'Выйти',
    MY_CARS: 'Мои машины',
    Settings: 'Настройкии',
    Support_US: 'Помощь',
    WISHLIST: 'Избранное',
  login: 'Войти',
  loginTitile: 'Вход',
  skip: 'Пропустить',
  welcomeBack: 'Добро пожаловать в DWD!',
  welcomeText: 'Пожалуйста, войдите в свою учетную запись или создайте новую, чтобы продолжить.',
  welcomeToDWD: 'Добро пожаловать',
  onboarding1Description: 'Вы можете легко найти и купить идеальный автомобиль в приложении DWD.',
  onboarding1Title: 'Покупай',
  password: 'Пароль',
  onboarding2Description: 'С DWD вы можете продать свой автомобиль быстро и надежно.',
  onboarding2Title: 'Продавай',
  onboarding3Description: 'Find the best services in Dubai for your car and instantly make an appointment',//перевести
  onboarding3Title: 'Find a service',//перевестии
  forgotPassword: 'Забыли пароль?',
  next: 'Далее',
  mobileNumberOrEmail: 'Мобильный телефон или почта', createAccount: 'Зарегистрировать аккаунт',
  back: 'Назад',
  sell: 'Продать',
  booking: 'Бронь',
  buy: 'Купить',
  service: 'Сервисы',
  chat: 'Чат',
    generalRepair: 'Общий ремонт',
    recovery: 'Эвакуатор',
    specialOffers: 'Специальные предложения',
    storage: 'Парковка',
    tinting: 'Тонировка',
    detailing: 'Детейлинг', acRepair: 'Климат контроль',
    allServices: 'Все сервисы', battery: 'Батарея',
    brakes: 'Тормоза', carRent: 'Аренда авто',
    insurance: 'Страховка',
    intervalService: 'ТО',
    wheels: 'Колёса',
    wrapping: 'Плёнка & PPF'
);
