import 'package:untitled1/translate/translate_model.dart';

TranslateModel ruModel = const TranslateModel(
  Profile: 'Профиль',
  About_us: 'О приложении',
  Change_account_Image: 'Изменить фото профиля',
  Change_account_name: 'Изменить имя',
  Change_app_language: 'Сменить язык',
  Delete_account: 'Удалить аккаунт',
  FAQ: 'FAQ',
  Help_Feedback: 'Обратная связь',
  Information: 'Информация',
  Log_out: 'Выйти',
  MY_CARS: 'Мои машины',
  Settings: 'Настройкии',
  Support_US: 'Помощь',
  WISHLIST: 'Избранное',
  login: 'Войти',
  loginTitile: 'Вход',
  skip: 'Пропустить',
  welcomeBack: 'Добро пожаловать в DWD!',
  welcomeText:
      'Пожалуйста, войдите в свою учетную запись или создайте новую, чтобы продолжить.',
  welcomeToDWD: 'Добро пожаловать',
  onboarding1Description:
      'Вы можете легко найти и купить идеальный автомобиль в приложении DWD.',
  onboarding1Title: 'Покупай',
  password: 'Пароль',
  onboarding2Description:
      'С DWD вы можете продать свой автомобиль быстро и надежно.',
  onboarding2Title: 'Продавай',
  onboarding3Description:
      'Find the best services in Dubai for your car and instantly make an appointment', //перевести
  onboarding3Title: 'Find a service', //перевестии
  forgotPassword: 'Забыли пароль?',
  next: 'Далее',
  mobileNumberOrEmail: 'Мобильный телефон или почта',
  createAccount: 'Зарегистрировать аккаунт',
  back: 'Назад',
  sell: 'Продать',
  booking: 'Бронь',
  buy: 'Купить',
  service: 'Сервисы',
  chat: 'Чат',
  generalRepair: 'Общий\nремонт',
  recovery: 'Эвакуатор',
  specialOffers: 'Специальные предложения',
  storage: 'Парковка',
  tinting: 'Тонировка',
  detailing: 'Детейлинг',
  acRepair: 'Климат\nконтроль',
  allServices: 'Все сервисы',
  battery: 'Батарея',
  brakes: 'Тормоза',
  carRent: 'Аренда\nавто',
  insurance: 'Страховка',
  intervalService: 'ТО',
  wheels: 'Колёса',
  wrapping: 'Плёнка\n& PPF',
  createOne: ' Создать',
  Already_have_an_account_q: 'Уже есть аккаунт?',
  Dont_have_an_account_q: 'Нет аккаунта?',
  trust: 'Надёжность',
  safety: 'Безопасность',
  transparency: 'Прозрачность',
  sellBanner1: 'Точная оценка\nавтомобиля,без\nфейковых офферов\nи рекламы.',
  sellBanner2:
      'Законные сделки\nи полная оплата,\nс защитой\nот мошеннечества.',
  sellBanner3: 'Лучшее предложение\nпо вашему авто\nи поддержка\n24/7.',
  sellBannerTitle: 'Поможем продать любой автомобиль в Дубае, ОАЭ',
  inStock: 'В наличии',
  body: 'Кузов',
  motorsTrim: 'Двигатель',
  kilometers: 'Пробег',
  serviceContract: 'Контракт на обслуживание',
  warranty: 'Гарантия',
  color: 'Цвет',
  description: 'Описание',
  transmission: 'Коробка передач',
  regionalSpecs: 'Регион',
  carDetails: 'Характеристики',
  year: 'Год',
  call: 'Вызов',
  moreCars: 'Другие автомобили',
  buyCarBannerPath: 'assets/ru_buy_banner.png',
  spot: 'Быстрая сделка',
  spotText:
      'Мы проведем комплексную оценку вашего автомобиля и предложим лучшую цену. Вы можете получить эти деньги быстро и не ждать конечного покупателя.',
  consignmentText:
      'Позвольте нам продать машину за вас. Прием на комиссию является безопасным способом продажи автомобиля. Мы занимаемся всеми аспектами продажи от вашего имени, листинг, продажа, доставка. Вам остается лишь подтвердить сделку. ',
  consignment: 'Комиссия',
  cancel: 'Отменить',
  change: 'Изменить',
  prePuschaseIncpection: 'Диагностика',
  bodyRepairAndPaint: 'Кузов и\nпокраска',
  add: 'Добавить',
  selectCar: 'Выбрать машину',
  addDelivery: 'Доставить авто',
  addPickup: 'Забрать авто',
  email: 'Эл. почта',
  extras: 'Дополнительные услуги',
  included: 'Включено',
  book: 'Забронировать',
  bookingText:
      'Мастерская расположена на территории JVC.\nМы вышлем вам точный адрес после\nподтверждения бронирования.',
  mobilePhone: 'Номер телефона',
  ownerEmail: 'Почта владельца',
  ownerName: 'Имя владельца',
  ownerPhone: 'Номер владельца',
  selectDate: 'Выберите желаемую дату и время',
      send: 'Отправить',
  was: 'было',
  stillForSale: 'Ещё продается?',
  isExchangePosible: 'Возможен обмен?',
  whereCarIViewIt: 'Могу ли посмотреть?',
  fullServiceHistory: 'Полная сервисная история',
  noAccident: 'Без ДТП',
  brand: 'Марка авто',
  giveCarName: 'Дайте название автомобилю',
  carReg: 'Регистрационный номер',
  carName: 'Имя машины',

newCar: 'Новая машина',
  model: 'Модель',
  askSeller: 'Спросите продавца',
      requestSent: 'Запрос отправлен!',
      close: 'Закрыть',
);
