name: untitled1
description: A new Flutter project.
publish_to: 'none'


version: 2.0.1+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider:
  dio:
  cupertino_icons:
  flutter_rating_bar:
  json_annotation:
  json_serializable:
  flutter_styled_toast:
  svg_flutter:
  awesome_extensions:
  crypto: ^3.0.3
  flutter_cupertino_datetime_picker: ^3.0.0
  flutter_svg:
  pin_code_fields:
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/design/images/
    - assets/svg/
    - image/
    - assets/


