name: untitled1
description: A new Flutter project.
publish_to: 'none'


version: 3.0.1+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_cupertino_datetime_picker: ^3.0.0
  provider:
  dio:
  get:
  svg_flutter:
  uuid:
  url_launcher:
  image_picker:
  flutter_secure_storage:
  flutter_multi_formatter: ^2.12.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/


