class UserModel {
  final name;
  final email;
  final age;
  final freelancer;
  final last_login;
  final password_hash;
  final city;
  final country;
  final date_of_burn;
  final avatar;
  final spheres;
  final skills;
  final education;
  final experience;
  final about_me;
  final client_visiting;
  final servises;
  final rating;
  final reviews;
  final email_succes;
  UserModel(
      {required this.email,
      required this.city,
      required this.password_hash,
      required this.name,
      required this.email_succes,
      required this.rating,
      required this.servises,
      required this.client_visiting,
      required this.about_me,
      required this.experience,
      required this.education,
      required this.spheres,
      required this.freelancer,
      required this.skills,
      required this.avatar,
      required this.date_of_burn,
      required this.country,
      required this.age,
      required this.last_login,
      required this.reviews});
}
