import 'package:untitled1/model/translate_model.dart';

TranslateModel enTranslate = TranslateModel(Request: 'Request', Login: 'Login', About_me: 'About me', Add_a_photo_to_your_profile: 'Add a photo to your profile', Add_another_Service: 'Add another Service', Add_comment: 'Add comment', Add_time_slots_for_appointment: 'Add time slots for appointment', All_applications: 'All applications', All_services: 'All services', Application_name: 'Application name', Application_name_q: 'Application name?', As_a_contractor: 'As a contractor', As_a_customer: 'As a customer', Beauty_and_wellness: 'Beauty and wellness', Become_a_contractor: 'Become a contractor', By_cash: 'By cash', By_date: 'By date', By_Service: 'By Service', By_using_the_app_you_agree_to_the: 'By using the app you agree to the', Can_be_done_remotely: 'Can be done remotely', Cancel_order: 'Cancel order', Category: 'Category', City: 'City', City_house_number_street: 'City, house number,street', City_search: 'City search', Clients_will_be_able_to_make_an_appointment_for_a_certain_time: 'Clients will be able to make an appointment for a certain time', Closed_for_responses: 'Closed for responses', Confirm_your_email: 'Confirm your email', Congratulations: 'Congratulations', Congratulations_you_have_become_a_professional: 'Congratulations you have become a professional', hour: 'hour', Consulting: 'Consulting', Continue: 'Continue', Contractors: 'Contractors', create_a_request: 'create a request', reviews: 'reviews', search: 'search', Create_an_application: 'Create an application', Create_orders_and_find_the_best_professionals: 'Create orders and find the best professionals', Create_the_same: 'Create the same', Creation_date: 'Creation date', Customer: 'Customer', Date_and_time: 'Date and time', Date_of_birth: 'Date of birth', Delete_a_profile: 'Delete a profile', Description: 'Description', Edit_a_photo: 'Edit a photo', Education: 'Education', Enter_an_email: 'Enter an email', Enter_the_city: 'Enter the city', Enter_your_name: 'Enter your name', Enter_your_password: 'Enter your password', Exit: 'Exit', Experience: 'Experience', Fill_in_the_services_and_prices: 'Fill in the services and prices', From: 'From', From_where: 'From where', Household: 'Household', How_do_you_want_to_register_q: 'How do you want to register?', How_much_are_you_willing_to_pay_q: 'How much are you willing to pay?', How_to_introduce_you_to_customers_q: 'How to introduce you to customers?', List_of_cities: 'List of cities', Location: 'Location', more: 'more', My_applications: 'My applications', Newest_first: 'Newestfirst', Now_you_can_fulfill_orders: 'Now you can fulfill orders', Oldest_first: 'Oldest  first', Open: 'Open', Order_details: 'Order details', Order_number: 'Order number', outcall_service: 'outcall service', Payment: 'Payment', Photo: 'Photo', Photo_can_be_added_later: 'Photo can be added later', Please_enter_your_details: 'Please enter your details', popular: 'popular', Popular_cities: 'Popular cities', Prices: 'Prices', Profile: 'Profile', Real_estate_car_goods: 'Realestate car goods', Recent_applications: 'Recent applications', Recent_services: 'Recent services', Register: 'Register', Rent_or_sale: 'Rent or sale', Repair_and_construction: 'Repair and construction', Resend_the_code_via: 'Resend the code via', Reset: 'Reset', Respond: 'Respond', Responses: 'Responses', review: 'review', Reviews: 'Reviews', Save: 'Save', Search_area: 'Search area', Search_for_orders: 'Search for orders', Select: 'Select', Select_a_category: 'Select a category', Select_the_date_and_time: 'Select the date and time', Select_the_dates: 'Select the dates', Select_the_job_categories_you_want_to_work_in: 'Select the job categories you want to work in', Select_working_hours: 'Select working hours', Send_a_new_code: 'Send a new code', Service: 'Service', Service_name: 'Service name', Set_the_price: 'Set the price', Settings: 'Settings', Show_the_applications: 'Show the applications', Similar_orders: 'Similar orders', Skills: 'Skills', Start: 'Start', step_from_to: 'step from to', symbols: 'symbols', This_way_customers_will_better_understand_your_skills: 'This way customers will better  understand your skills', Till: 'Till', Time_slots_for_online_booking: 'Time slots for online booking', To_be_trusted_make_sure_you_use_a_good_quality_photo: 'To be trusted make sure you use a good quality photo', To_be_trusted_provide_reliable_information: 'To be trusted provide reliable information', Transportations: 'Transportations', Upload_a_photo: 'Upload a photo', View_all_services_and_prices: 'View all services and prices', View_all_the_information: 'View all the information', View_the_application: 'View the application', View_the_profile: 'View the profile', Was_online_at: 'Was online at', What_do_you_want_to_do_q: 'What do you want to do?', What_kind_of_help_do_you_need_q: 'What kind of help do you need?', When_is_it_necessary_q: 'When is it necessary?', Where: 'Where', Where_is_it_necessary_q: 'Where is it necessary?', Where_to_deliver_q: 'Where to deliver?', Would_you_like_to_add_something_to_your_order_q: 'Would you like to add something to your order?', Write_down_why_it_is_worth_choosing_you: 'Write down why it is worth choosing you', Write_important_details_for_the_specialist: 'Write important details for the specialist', You_can_fill_it_out_later: 'You can fill it out later', Your_application_has_been_successfully_created: 'Your application has been successfully created', Your_city: 'Your city', your_email_has_been: 'your email has been', Your_name_and_surname: 'Your name and surname', Your_order_is_almost_ready: 'Your order is almost ready', Privace_policy: 'Privace policy');

    //popular: Популярное,
// Repair and construction: Ремонт и строительство,
// search: Поиск,
// create_a_request: создать заявку,
// Красота и здоровье: Beauty and wellness,
// Бытовые услуги: Household service,
// Консультация: Consulting services,
// Перевозки: Transportations,
// Аренда или продажа: Rent or sale,
// Недвижимости, автомобиля, вещей: Real estate, car, goods,
// Еще: more,
// Последние заявки: Recent applications,
// Последние услуги: Recent services,
// Создать заявку: Create an application,
// Чем вам помочь?: What kind of help do you need?
// Название заявки: Application name,
// Как будет называться заявка?: Application name?
// Шаг n из m: Шаг n из m, ??? step from…to...
// Когда нужно?: When is it necessary?,
// Выберите дату и время: Select the date and time,
// Дата и время: Date and time,
// Сбросить: Reset,
// Где нужно?: Where is it necessary?,
// Город, дом, улица: City, house number, street,
// Можно выполнить удаленно: Can be done remotely,
// Куда нужно доставить?: Where to deliver?
// Откуда: From where,
// Куда: Where,
// Продолжить: Continue,
// Выбрать: Select
// Сколько готовы заплатить?: How much are you willing to pay?,
// От: From,
// До: Till,
// Остались пожелания к заказу?: Would you like to add something to your order?
// Напишите важные детали для специалиста: Add comment,
// Заказ почти готов: Your order is almost ready,
// Введите имя: Enter your name,
// Введите email: Enter an email,
// Ваша заявка успешна создана!: Your application has been successfully created!,
// Посмотреть заявку: View the application,
// Открыто: Open,
// Категория: Category,
// Описание: Description,
// Пожелание: Request,
// Начать: Start,
// Фото: Photo,
// Наличными: By cash,
// Оплата: Payment,
// Номер заказа: Order number,
// Дата создания: Creation date,
// Откликнуться: Respond,
// Создать такое же: Create the same,
// Заказчик: Customer,
// >5+n отзывов: >5 reviews,
// 1-4 отзыва: 1-4 review,
// Похожие заказы: Similar orders,
// Все заявки: All applications,
// По дате: By date,
// По услуге: By Service, Расположение: Location,
// час: hour,
// По дате: By date,
// Сначала новые: Newest first
// Сначала старые: Oldest first,
// Область поиска: Search area,
// Показать заявки: Show the applications,
// Все услуги: All services,
// Мои заявки: My applications,
// Отклики: Responses,
// Специалисты: Contractors,
// Закрыта для откликов: ​​ Closed for responses,
// Детали заказа: Order details,
// Отменить заказ: Cancel order,
// Настройки: Settings,
// Смотреть все сведения: View all the information,
// Смотреть все услуги и цены: View all services and prices,
// Почта подтверждена: your e-mail has been confirmed, Был в сети сегодня в 18:00: Was online at 18:00,
// Прайс-лист: Prices,
// Создавайте заказы и находите лучших исполнителей: Create orders and find the best professionals,
// Зарегистрироваться: Register,
// Войти: Login,
// Как хотите зарегистрироваться?: How do you want to register?,
// Как исполнитель: As a contractor,
// Как заказчик: As a customer,
// Пожалуйста, введите ваши данные: Please enter your details,
// Введите Имя: Enter your name,
// Введите Город: Enter the city,
// Введите пароль: Enter your password,
// Используя приложение, вы соглашаетесь с Политикой конфиденциальности: By using the app, you agree to the Privacy policy,
// Подтвердите свой email: Confirm your email,
// Повторно отправить код через mm:ss: Resend the code via mm:ss,
// Отправить новый код: Send a new code,
// Стать исполнителем: Become a contractor,
// Как вас представлять заказчикам?: How to introduce you to customers?,
// Чтобы заказчики доверяли вам, укажите достоверную информацию: To be trusted, provide reliable information,
// Ваше ФИО: Your name and surname
// Ваш город: Your city,
// Дата рождения: Date of birth,
// Город: City,
// Поиск города: City search,
// Популярные города: Popular cities,
// Список городов: List of cities,
// Добавьте фото в профиль: Add a photo to your profile,
// Пользователям с хорошей фотографией больше доверяют.: To be trusted make sure you use a good quality photo
// Загрузить фотографию: Upload a photo,
// Фото можно добавить позже: Photo can be added later,
// Чем хотите заниматься?: What do you want to do?,
// Выберите категории заданий, в которых хотите работать: Select the job categories you want to work in,
// Расскажите о себе: Аbout me,
// Напишите, почему стоит выбрать именно вас.: Write down why it is worth choosing you.,
// Навыки: Skills,
// Образование: Education,
// Опыт: Experience,
// О себе: About me,
// Выезд к клиенту: outcall service
// Напишите важные детали для специалиста: Write important details for the specialist,
// 0 / 1000 символов: 0 / 1000 symbols,
// Заполните услуги и цены: Fill in the services and prices,
// Так заказчики будут лучше понимать ваши навыки,: This way customers will better understand your skills.,
// Категория: Category ,
// Выберите категорию: Select a category,
// Название услуги: Service name,
// Услуга: Service,
// Укажите цену: Set the price,
// Добавить временные слоты для онлайн-записи: Add time slots for appointment,
// Добавить еще Услугу: Add another Service,
// Можете заполнить позже: You can fill it out later,
// Временные слоты для онлайн-записи: Time slots for online booking
// Клиенты смогут сами записываться к вам на определенное время: Clients will be able to make an appointment for a certain time,
// Выберите даты, в которые будете работать: Select the dates,
// Выберите время работы: Select working hours,
// Сохранить: Save,
// Можете заполнить позже: You can fill it out later,
// Поздравляем, вы стали исполнителем!: ​​ Congratulations, you have become a professional!,
// Поздравляем: Congratulations,
// Теперь вы можете выполнять заказы: Now you can fulfill orders,
// Искать заказы: Search for orders,
// Посмотреть профиль: View the profile,
// Профиль: Profile
// Отзывы: Reviews,
// Удалить профиль: Delete a profile,
// Выйти: Exit,
// Изменить фотографию: Edit a photo,