import 'package:untitled1/model/translate_model.dart';

TranslateModel ruTranslate = TranslateModel(
    Request: 'Пожелание',
    Privace_policy: 'политика конфединциальности',
    Login: 'Войти',
    About_me: 'Обо мне',
    Add_a_photo_to_your_profile: 'Добавьте фото в профиль',
    Add_another_Service: 'Добавить еще Услугу',
    Add_comment: 'Напишите важные детали для специалиста',
    Add_time_slots_for_appointment:
        'Добавить временные слоты для онлайн-записи',
    All_applications: 'Все заявки',
    All_services: 'Все услуги',
    Application_name: 'Название заявки',
    Application_name_q: 'Как будет называться заявка?',
    As_a_contractor: 'Как исполнитель',
    As_a_customer: 'Как заказчик',
    Beauty_and_wellness: 'Красота и здоровье',
    Become_a_contractor: 'Стать исполнителем',
    By_cash: 'По цене',
    By_date: 'По дате',
    By_Service: 'По услуге',
    By_using_the_app_you_agree_to_the: 'Используя приложение вы соглашаетесь с',
    Can_be_done_remotely: 'Можно выполнить удаленно',
    Cancel_order: 'Отменить заказ',
    Category: 'Категория',
    City: 'Город',
    City_house_number_street: 'Город, дом, улица',
    City_search: 'Поиск города',
    Clients_will_be_able_to_make_an_appointment_for_a_certain_time:
        'Клиенты смогут сами записываться к вам на определенное время',
    Closed_for_responses: 'Закрыта для откликов',
    Confirm_your_email: 'Подтвердите ваш email',
    Congratulations: 'Поздравляем',
    Congratulations_you_have_become_a_professional:
        'Поздравляем, вы стали исполнителем!',
    hour: 'час',
    Consulting: 'Консультация',
    Continue: 'Продолжить',
    Contractors: 'Специалисты',
    create_a_request: 'Создать заявку',
    reviews: 'отзывов',
    search: 'поиск',
    Create_an_application: 'Создать заявку',
    Create_orders_and_find_the_best_professionals:
        'Создавайте заказы и находите лучших исполнителей',
    Create_the_same: 'Создать такое же',
    Creation_date: 'Дата создания',
    Customer: 'Заказчик',
    Date_and_time: 'Дата и время',
    Date_of_birth: 'Дата рождения',
    Delete_a_profile: 'Удалить профиль',
    Description: 'Описание',
    Edit_a_photo: 'Изменить фото',
    Education: 'Образование',
    Enter_an_email: 'Введите email',
    Enter_the_city: 'Укажите город',
    Enter_your_name: 'Введите имя',
    Enter_your_password: 'Введите пароль',
    Exit: 'Выход',
    Experience: 'Опыт',
    Fill_in_the_services_and_prices: 'Заполните услуги и цены',
    From: 'От',
    From_where: 'откуда',
    Household: 'Бытовые услуги',
    How_do_you_want_to_register_q: 'Как хотите зарегистрироваться?',
    How_much_are_you_willing_to_pay_q: 'Сколько готовы заплатить?',
    How_to_introduce_you_to_customers_q: 'Как вас представлять заказчикам?',
    List_of_cities: 'Список городов',
    Location: 'Расположение',
    more: 'Ещё',
    My_applications: 'Мои заявки',
    Newest_first: 'Сначала новые',
    Now_you_can_fulfill_orders: 'Теперь вы можете выполнять заказы',
    Oldest_first: 'Сначала старые',
    Open: 'Открыто',
    Order_details: 'Детали заявки',
    Order_number: 'Номер заявки',
    outcall_service: 'Выезд к клиенту',
    Payment: 'Оплата',
    Photo: 'Фото',
    Photo_can_be_added_later: 'Фото можно добавить позже',
    Please_enter_your_details: 'Пожалуйста, введите ваши данные',
    popular: 'Популярное',
    Popular_cities: 'Популярные города',
    Prices: 'Цены',
    Profile: 'Профиль',
    Real_estate_car_goods: 'Недвижимости, автомобиля, вещей',
    Recent_applications: 'Последние заявки',
    Recent_services: 'Последние услуги',
    Register: 'Регистрация',
    Rent_or_sale: 'Аренда или продажа',
    Repair_and_construction: 'Ремонт и строительство',
    Resend_the_code_via: '',
    Reset: 'Сбросить',
    Respond: 'Откликнуться',
    Responses: 'Отклики',
    review: 'отзыв',
    Reviews: 'Отзывы',
    Save: 'Сохранить',
    Search_area: 'Область поиска',
    Search_for_orders: 'Искать заказы',
    Select: 'Выбрать',
    Select_a_category: 'Выбрать категорию',
    Select_the_date_and_time: 'Выбрать дату и время',
    Select_the_dates: 'Выберите даты',
    Select_the_job_categories_you_want_to_work_in:
        'Выберите категории заданий, в которых хотите работать',
    Select_working_hours: 'Выберите рабочие часы',
    Send_a_new_code: "Отправить новый код",
    Service: 'Услуга',
    Service_name: 'Название услуги',
    Set_the_price: 'Укажите стоимость',
    Settings: 'Настройки',
    Show_the_applications: 'Показать заявки',
    Similar_orders: 'Похожие заказы',
    Skills: 'Навыки',
    Start: 'Начать',
    step_from_to: 'Шаг',
    symbols: 'символов',
    This_way_customers_will_better_understand_your_skills:
        'Так заказчики будут лучше понимать ваши навыки.',
    Till: 'До',
    Time_slots_for_online_booking: 'Временные слоты для онлайн-записи',
    To_be_trusted_make_sure_you_use_a_good_quality_photo:
        'Пользователям с хорошей фотографией больше доверяют.',
    To_be_trusted_provide_reliable_information:
        'Чтобы заказчики доверяли вам, укажите достоверную информацию',
    Transportations: 'Перевозки',
    Upload_a_photo: 'Загрузить фото',
    View_all_services_and_prices: 'Смотреть все услуги и цены:',
    View_all_the_information: 'Смотреть все сведения',
    View_the_application: 'Смотреть заявку',
    View_the_profile: 'Смотреть профиль',
    Was_online_at: 'Был онлайн в',
    What_do_you_want_to_do_q: 'Чем хотите заниматься?',
    What_kind_of_help_do_you_need_q: 'Чем вам помочь?',
    When_is_it_necessary_q: 'Когда нужно?',
    Where: 'Куда',
    Where_is_it_necessary_q: 'Где нужно?',
    Where_to_deliver_q: 'Куда нужно доставить?',
    Would_you_like_to_add_something_to_your_order_q:
        'Остались пожелания к заказу?',
    Write_down_why_it_is_worth_choosing_you:
        'Напишите, почему стоит выбрать именно вас.',
    Write_important_details_for_the_specialist:
        'Напишите важные детали для специалиста',
    You_can_fill_it_out_later: 'Вы можете заполнить это позже',
    Your_application_has_been_successfully_created:
        'Ваша заявка успешна создана!',
    Your_city: 'Ваш город',
    your_email_has_been: 'Почта подтверждена',
    Your_name_and_surname: 'Ваше ФИО',
    Your_order_is_almost_ready: 'Ваша заявка почти готова');

// Последние заявки: Recent applications,
// Последние услуги: Recent services,
// Создать заявку: Create an application,
// Чем вам помочь?: What kind of help do you need?
// Название заявки: Application name,
// Как будет называться заявка?: Application name?
// Шаг n из m: Шаг n из m, ??? step from…to...
// Когда нужно?: When is it necessary?,
// Выберите дату и время: Select the date and time,
// Дата и время: Date and time,
// Сбросить: Reset,
// Где нужно?: Where is it necessary?,
// Город, дом, улица: City, house number, street,
// Можно выполнить удаленно: Can be done remotely,
// Куда нужно доставить?: Where to deliver?
// Откуда: From where,
// Куда: Where,
// Продолжить: Continue,
// Выбрать: Select
// Сколько готовы заплатить?: How much are you willing to pay?,
// От: From,
// До: Till,
// Остались пожелания к заказу?: Would you like to add something to your order?
// Напишите важные детали для специалиста: Add comment,
// Заказ почти готов: Your order is almost ready,
// Введите имя: Enter your name,
// Введите email: Enter an email,
// Ваша заявка успешна создана!: Your application has been successfully created!,
// Посмотреть заявку: View the application,
// Открыто: Open,
// Категория: Category,
// Описание: Description,
// Пожелание: Request,
// Начать: Start,
// Фото: Photo,
// Наличными: By cash,
// Оплата: Payment,
// Номер заказа: Order number,
// Дата создания: Creation date,
// Откликнуться: Respond,
// Создать такое же: Create the same,

// >5+n отзывов: >5 reviews,
// 1-4 отзыва: 1-4 review,
// Похожие заказы: Similar orders,
// Все заявки: All applications,
// По дате: By date,
// По услуге: By Service,
// час: hour,
// По дате: By date,
// Сначала новые: Newest first
// Сначала старые: Oldest first,
// Область поиска: Search area,
// Показать заявки: Show the applications,
// Все услуги: All services,
// Мои заявки: My applications,
// Отклики: Responses,
// Специалисты: Contractors,
// Закрыта для откликов: ​​ Closed for responses,
// Детали заказа: Order details,
// Отменить заказ: Cancel order,
// Настройки: Settings,
// Смотреть все сведения: View all the information,
// Смотреть все услуги и цены: View all services and prices,
// Почта подтверждена: your e-mail has been confirmed, Был в сети сегодня в 18:00: Was online at 18:00,
// Прайс-лист: Prices,
// Создавайте заказы и находите лучших исполнителей: Create orders and find the best professionals,
// Зарегистрироваться: Register,
// Войти: Login,
// Как хотите зарегистрироваться?: How do you want to register?,
// Как исполнитель: As a contractor,
// Как заказчик: As a customer,
// Пожалуйста, введите ваши данные: Please enter your details,
// Введите Имя: Enter your name,
// Введите Город: Enter the city,
// Введите пароль: Enter your password,
// Используя приложение, вы соглашаетесь с Политикой конфиденциальности: By using the app, you agree to the Privacy policy,
// Подтвердите свой email: Confirm your email,
// Повторно отправить код через mm:ss: Resend the code via mm:ss,
// Отправить новый код: Send a new code,
// Стать исполнителем: Become a contractor,
// Как вас представлять заказчикам?: How to introduce you to customers?,
// Чтобы заказчики доверяли вам, укажите достоверную информацию: To be trusted, provide reliable information,
// Ваше ФИО: Your name and surname
// Ваш город: Your city,
// Дата рождения: Date of birth,
// Город: City,
// Поиск города: City search,
// Популярные города: Popular cities,
// Список городов: List of cities,
// Добавьте фото в профиль: Add a photo to your profile,
// Пользователям с хорошей фотографией больше доверяют.: To be trusted make sure you use a good quality photo
// Загрузить фотографию: Upload a photo,
// Фото можно добавить позже: Photo can be added later,
// Чем хотите заниматься?: What do you want to do?,
// Выберите категории заданий, в которых хотите работать: Select the job categories you want to work in,
// Расскажите о себе: Аbout me,
// Напишите, почему стоит выбрать именно вас.: Write down why it is worth choosing you.,
// Навыки: Skills,
// Образование: Education,
// Опыт: Experience,
// О себе: About me,
// Выезд к клиенту: outcall service
// Напишите важные детали для специалиста: Write important details for the specialist,
// 0 / 1000 символов: 0 / 1000 symbols,
// Заполните услуги и цены: Fill in the services and prices,
// Так заказчики будут лучше понимать ваши навыки,: This way customers will better understand your skills.,
// Категория: Category ,
// Выберите категорию: Select a category,
// Название услуги: Service name,
// Услуга: Service,
// Укажите цену: Set the price,
// Добавить временные слоты для онлайн-записи: Add time slots for appointment,
// Добавить еще Услугу: Add another Service,
// Можете заполнить позже: You can fill it out later,
// Временные слоты для онлайн-записи: Time slots for online booking
// Клиенты смогут сами записываться к вам на определенное время: Clients will be able to make an appointment for a certain time,
// Выберите даты, в которые будете работать: Select the dates,
// Выберите время работы: Select working hours,
// Сохранить: Save,
// Можете заполнить позже: You can fill it out later,
// Поздравляем, вы стали исполнителем!: ​​ Congratulations, you have become a professional!,
// Поздравляем: Congratulations,
// Теперь вы можете выполнять заказы: Now you can fulfill orders,
// Искать заказы: Search for orders,
// Посмотреть профиль: View the profile,
// Профиль: Profile
// Отзывы: Reviews,
// Удалить профиль: Delete a profile,
// Выйти: Exit,
// Изменить фотографию: Edit a photo,
